### ISSUE TITLE
Twitter sucks

### ISSUE THREAD

**Issue by billevenson** [andrew-shackelford/Surrender-Index#8]
Any chance to post to Mastodon? Or Bluesky? Or hell, even Threads is better than the Twitter horror show.

**Comment by TomCasavant** [comment]
> Any chance to post to Mastodon? Or Bluesky? Or hell, even Threads is better than the Twitter horror show.

I ported this code to a couple of Mastodon-based bots (https://github.com/TomCasavant/Surrender-Index)

- [@surrender_index@tomkahe.com](https://tomkahe.com/@surrender_index)
- [@surrender_idx90@tomkahe.com](https://tomkahe.com/@surrender_idx90)

I will have them bridged to Bluesky as well if that's your preferred platform, though I have to wait til those accounts are 2 weeks old. When they are it'll be [@surrender-index.tomkahe.com.ap.brid.gy](https://bsky.app/profile/surrender-index.tomkahe.com.ap.brid.gy) and [@surrender-idx90.tomkahe.com.ap.brid.gy](https://bsky.app/profile/surrender-idx90.tomkahe.com.ap.brid.gy)
https://fed.brid.gy/docs#fediverse-cant-find
> As basic spam filters, Bridgy Fed requires a couple things on your profile:
    - a profile picture
    - if your server advertises account age (like Mastodon), your account needs to be at least two weeks old 
    
EDIT: Both are bridged to Bluesky now

**Comment by andrew-shackelford** [comment]
Hey Tom, thanks for doing this! I'll update the README to add a link to your repo and those accounts.
